# Exploring Codebase Skill - Machine-Readable Manifest
# Version: 1.0.0

name: "exploring-codebase"
version: "1.0.0"
description: |
  Autonomous two-phase codebase exploration - first discovers natural perspectives
  (layers, components, boundaries), then dispatches adaptive deep-dive explorers
  based on what was discovered. Synthesizes findings into actionable insights.

# When to trigger this skill
trigger:
  - "Need to understand how a feature/system works across the codebase"
  - "Starting work on unfamiliar codebase or component"
  - "Planning changes that span multiple layers/components"
  - "User asks 'how does X work?' for non-trivial X"
  - "Need architecture understanding before implementation"

# Valid reasons to skip (keep minimal)
skip_when:
  - "Pure reference lookup (function signature, type definition)"
  - "Checking if specific file exists (yes/no question)"
  - "Reading error message from known file location"

# INVALID skip reasons - these trigger red flags
invalid_skip_reasons:
  - reason: "I already know the architecture"
    counter: "Prior knowledge is incomplete. Discovery validates assumptions and reveals what changed."
    severity: "high"
    
  - reason: "Simple question about location"
    counter: "Location without context is incomplete. One exploration answers current + future questions."
    severity: "medium"
    
  - reason: "Production emergency, no time"
    counter: "High stakes demand MORE rigor. 6-10 min discovery prevents hours of wrong assumptions."
    severity: "critical"
    
  - reason: "Colleague told me the structure"
    counter: "High-level ≠ implementation details. Discovery finds what they forgot or didn't know."
    severity: "high"
    
  - reason: "Grep is faster for this"
    counter: "One systematic exploration > multiple ad-hoc greps + follow-up questions."
    severity: "medium"
    
  - reason: "This is overkill"
    counter: "Incomplete understanding compounds. The cost of skipping > cost of doing."
    severity: "medium"
    
  - reason: "I'll explore progressively if I get stuck"
    counter: "Reactive exploration is less efficient than proactive discovery."
    severity: "low"
    
  - reason: "Let me just quickly check..."
    counter: "Ad-hoc investigation trap. Systematic beats quick every time."
    severity: "medium"

# Embedded agents
agents:
  - path: "agents/discovery-agent.md"
    name: "discovery-agent"
    role: "phase-1"
    description: "Discovers architecture, components, layers, and boundaries"
    model: "haiku"
    tools: ["Read", "Glob", "Grep", "Bash"]
    spawn: "single"
    
  - path: "agents/deep-dive-agent.md"
    name: "deep-dive-agent"
    role: "phase-2"
    description: "Deep exploration of specific component/layer"
    model: "sonnet"
    tools: ["Read", "Glob", "Grep"]
    spawn: "dynamic"  # N instances based on phase-1 discoveries

# Hooks scoped to this skill
hooks:
  PreToolUse:
    - matcher: "Bash"
      script: "hooks/pre-tool-use.js"
      timeout: 5000
      purpose: "Prevent grep/find shortcuts that bypass systematic discovery"
      
    - matcher: "Grep"
      script: "hooks/validate-grep-context.js"
      timeout: 3000
      purpose: "Ensure grep is used for exploration, not as shortcut"
      
  SubagentStop:
    - script: "hooks/validate-completion.js"
      timeout: 5000
      purpose: "Validate subagent completed all required sections"
      
  Stop:
    - script: "hooks/validate-exit-criteria.js"
      timeout: 5000
      purpose: "Verify all exit criteria met before skill completion"

# Platform-specific configurations
platforms:
  claude-code:
    native: true
    install_path: "~/.claude/skills/exploring-codebase/"
    agents_path: "~/.claude/agents/"
    hooks_merge: true
    
# Output expectations
output:
  format: "markdown"
  template: "templates/synthesis-output.md"
  required_sections:
    - "## Architecture Overview"
    - "## Component Map"
    - "## [TARGET] Analysis"
    - "## Integration Points"
    - "## Recommendations"

# Testing
tests:
  scenarios: "tests/scenarios.yaml"
  stress_test: "tests/stress-test.md"
