# Exploring Codebase Skill - Machine-Readable Manifest

name: "exploring-codebase"
description: |
  Systematic codebase exploration that maps architecture, components, and dependencies.
  Use when you need to understand how a feature works across a codebase, explore an
  unfamiliar project's architecture, trace data flow through multiple layers, or plan
  changes that span several components. Maps the high-level structure first, then
  dispatches parallel agents to explore each area in depth. Produces a synthesis with
  file:line references, execution flows, and actionable recommendations.

# When to trigger this skill
trigger:
  - "understand this codebase"
  - "explore the architecture"
  - "how is this code organized"
  - "how does [feature] work across the system"
  - "give me an overview of this project"
  - "starting work on unfamiliar codebase or component"
  - "planning changes that span multiple layers/components"
  - "map the dependencies / module boundaries"
  - "trace how [data/request] flows through the system"

# Valid reasons to skip (keep minimal)
skip_when:
  - "Pure reference lookup (function signature, type definition)"
  - "Checking if specific file exists (yes/no question)"
  - "Reading a single known file"
  - "User explicitly asked for grep/find, not exploration"

# Embedded agents
agents:
  - path: "agents/discovery-agent.md"
    name: "discovery-agent"
    role: "phase-1"
    description: "Discovers architecture, components, layers, and boundaries"
    model: "haiku"
    tools: ["Read", "Glob", "Grep", "Bash"]
    spawn: "single"

  - path: "agents/deep-dive-agent.md"
    name: "deep-dive-agent"
    role: "phase-2"
    description: "Deep exploration of specific component/layer"
    model: "sonnet"
    tools: ["Read", "Glob", "Grep"]
    spawn: "dynamic"  # N instances based on phase-1 discoveries

# Hooks scoped to this skill
hooks:
  PreToolUse:
    - matcher: "Bash"
      script: "hooks/pre-tool-use.js"
      timeout: 5000
      purpose: "Prevent grep/find shortcuts that bypass systematic discovery"

    - matcher: "Grep"
      script: "hooks/validate-grep-context.js"
      timeout: 3000
      purpose: "Ensure grep is used for exploration, not as shortcut"

  SubagentStop:
    - script: "hooks/validate-completion.js"
      timeout: 5000
      purpose: "Validate subagent completed all required sections"

  Stop:
    - script: "hooks/validate-exit-criteria.js"
      timeout: 5000
      purpose: "Verify all exit criteria met before skill completion"

# Platform-specific configurations
platforms:
  claude-code:
    native: true
    install_path: "~/.claude/skills/exploring-codebase/"
    agents_path: "~/.claude/agents/"
    hooks_merge: true

# Output expectations
output:
  format: "markdown"
  template: "templates/synthesis-output.md"
  required_sections:
    - "## Architecture Overview"
    - "## Component Map"
    - "## [TARGET] Analysis"
    - "## Integration Points"
    - "## Recommendations"

# Testing
tests:
  scenarios: "tests/scenarios.yaml"
  stress_test: "tests/stress-test.md"
